print(" ")
print("   *   ")
print("  * *  ")
print(" *   * ")
print("*     *")
print("  aaaaaa")
print(" HHHHHH")
print(" HHHHHHHH")
print("     @@    ")
print("     ^     ")
print("  SSS * S")
print(" * SSSSSSS")
print(" *    0 SS")
print(" 0    S")
print("  0    *")
print("   *")
